CREATE TABLE [endur].[vw_currency]
(
   NAME NVARCHAR(MAX) NULL,
   ID_NUMBER INT NULL,
   DEFAULT_INDEX INT NULL,
   SPOT_INDEX INT NULL,
   CONVENTION INT NULL,
   HOLIDAY_ID INT NULL,
   BASE_UNIT INT NULL,
   ROUND INT NULL,
   DESCRIPTION NVARCHAR(MAX) NULL,
   ROUND_TYPE INT NULL,
   EURO INT NULL,
   EURO_CONVERSION FLOAT NULL,
   CURRENCY_ZONE INT NULL,
   EURO_SCENARIO_FLAG INT NULL,
   ADVANCE_RELEASE_DAYS INT NULL,
   LAST_UPDATE DATE NULL,
   PRECIOUS_METAL INT NULL,
   AUTO_CONVERSION_FLAG INT NULL,
   VERSION_NUMBER INT NULL
);
