CREATE TABLE [endur].[vw_dw_extraction_log]
(
   EXTRACTION_ID INT NULL,
   SIM_RUN_ID INT NULL,
   SIM_DEF_ID INT NULL,
   SCENARIO_SEQ_NUM INT NULL,
   REVISION INT NULL,
   ROW_CREATION DATE NULL,
   SYSTEM_DATE DATE NULL,
   RUN_TYPE INT NULL,
   SIM_DEF_NAME NVARCHAR(MAX) NULL,
   SCENARIO_NAME NVARCHAR(MAX) NULL,
   PFOLIO INT NULL,
   DB_STATUS INT NULL,
   EXTRACTION_STATUS INT NULL,
   EXTRACTION_TIMESTAMP DATE NULL,
   ETL_STATUS INT NULL,
   ETL_TIMESTAMP DATE NULL
)
