CREATE TABLE [endur].[vw_delivery_type]
(
   NAME NVARCHAR(MAX) NULL,
   ID_NUMBER INT NULL,
   SETTLE_TOOLSET INT NULL,
   PHYS_VALUATION_METHOD INT NULL,
   LAST_UPDATE DATE NULL,
   VERSION_NUMBER INT NULL,
   ALT_DELIVERY_CCY_ID INT NULL
)
