CREATE TABLE [endur].[vw_energy_conversion]
(
   PIPELINE_ID INT NULL,
   ZONE_ID INT NULL,
   LOCATION_ID INT NULL,
   EFFECTIVE_GMT_DATE DATE NULL,
   SRC_UNIT_ID INT NULL,
   DEST_UNIT_ID INT NULL,
   CONVERSION_FACTOR FLOAT NULL,
   CONVERSION_COMMENTS NVARCHAR(MAX) NULL,
   VERSION_NUMBER INT NULL,
   LAST_UPDATE DATE NULL,
   CONTRACTED_VALUE FLOAT NULL,
   REPLACEMENT_VALUE FLOAT NULL,
   FORECASTED_VALUE FLOAT NULL,
   ALLOCATED_VALUE FLOAT NULL
)
