CREATE TABLE [endur].[vw_gas_phys_loc_type]
(
   LOC_TYPE_ID INT NULL,
   LOC_TYPE_NAME NVARCHAR(MAX),
   LAST_UPDATE DATE NULL,
   VERSION_NUM INT NULL,
   LOC_TYPE_POOL_FLAG INT NULL,
   LOC_TYPE_OBA_FLAG INT NULL,
   AGGREGATE INT NULL,
   LOC_TYPE_CTP_FLAG INT NULL,
   PLANT_INLET INT NULL,
   PLANT_TAILGATE INT NULL,
   NON_SCHED_LOC INT NULL,
   FACILITY_LOC INT NULL
)
