CREATE TABLE [endur].[vw_idx_historical_fx_rates]
(
REFERENCE_CURRENCY_ID INT NULL,
LAST_UPDATE		DATE NULL,
FX_RATE_OFFER	FLOAT NULL,
FX_RATE_MID		FLOAT NULL,
FX_RATE_DATE	DATE NULL,
FX_RATE_BID		FLOAT NULL,
DATA_SET_TYPE	INT NULL,
CURRENCY_ID		INT NULL,
CURRENCY_CONVENTION		INT NULL
)
