CREATE TABLE [endur].[vw_idx_historical_prices]
(
	INDEX_ID INT NULL,
	RESET_DATE DATE NULL,
	PRICE FLOAT NULL,
	LAST_UPDATE DATE NULL,
	TIME INT NULL,
	START_DATE DATE NULL,
	END_DATE DATE NULL,
	YIELD_BASIS INT NULL,
	REF_SOURCE INT NULL,
	INDEX_LOCATION INT NULL
)
