CREATE TABLE [endur].[vw_instruments]
(
	VERSION_NUMBER	INT NULL,
	TOOLSET INT NULL,
	SUPPRESS_INS_TYPE_TRIGGER INT NULL,
	NAME NVARCHAR(MAX) NULL,
	LONGNAME NVARCHAR(MAX) NULL,
	LAST_UPDATE DATE NULL,
	ID_NUMBER INT NULL,
	DFLT_PX_MODEL INT NULL,
	BASE_INS_ID INT NULL
)
