CREATE TABLE [endur].[vw_loc_info_types]
(
	TYPE_NAME NVARCHAR(MAX) NULL,
	TYPE_ID INT NULL,
	SEC_GROUP_ID INT NULL,
	REQUIRED_FLAG INT NULL,
	PIPELINE_ID INT NULL,
	PICK_LIST_ID INT NULL,
	LAST_UPDATE DATE NULL,
	DISPLAY_ORDER INT NULL,
	DEFAULT_VALUE NVARCHAR(MAX) NULL,
	DATA_TYPE INT NULL,
	AUDIT_FLAG INT NULL
)
