CREATE TABLE [endur].[vw_portfolio]
(
	ID_NUMBER INT NULL,
	NAME NVARCHAR(MAX) NULL,
	LONG_NAME NVARCHAR(MAX) NULL,
	PORTFOLIO_TYPE INT NULL,
	RESTRICTED INT NULL,
	LAST_UPDATE	DATE NULL,
	PORTFOLIO_VERSION INT NULL,
	REQUIRES_STRATEGY INT NULL
)
