CREATE TABLE [endur].[vw_party_info_types]
(
	TYPE_ID	INT NULL,
	TYPE_NAME NVARCHAR(MAX) NULL,
	DATA_TYPE INT NULL,
	PARTY_CLASS	INT NULL,
	LAST_UPDATE DATE NULL,
	INT_EXT	INT NULL,
	REQUIRED_FLAG INT NULL,
	DEFAULT_VALUE NVARCHAR(MAX) NULL,
	PICK_LIST_ID INT NULL,
	SEC_GROUP_ID INT NULL,
	AUDIT_FLAG INT NULL,
	PARTY_ORDER INT NULL,
	VERSION_NUMBER INT NULL,
	MULTI_SELECT_FLAG INT NULL
)
