CREATE TABLE [endur].[vw_party]
(
	PARTY_ID INT NULL,
	INT_EXT	INT NULL,
	PARTY_CLASS	INT NULL,
	PARTY_STATUS INT NULL,
	SHORT_NAME NVARCHAR(MAX) NULL,
	LONG_NAME NVARCHAR(MAX) NULL,
	LAST_UPDATE	DATE NULL,
	PARTY_VERSION INT NULL,
	DEFAULT_PORTFOLIO_ID INT NULL,
	AGENCY_ACTIVITIES INT NULL,
	LINKED_PARTY_ID	INT NULL,
)
