CREATE TABLE [endur].[vw_ref_source]
(
	NAME NVARCHAR(MAX) NULL,
	ID_NUMBER INT NULL,
	PUB_ID INT NULL,
	DATE_SEQUENCE_ID INT NULL,
	PROJECTION_METHOD_ID INT NULL,
	LAST_UPDATE DATE NULL,
	ACTIVE INT NULL,
	VERSION_NUMBER INT NULL
)
