CREATE TABLE [endur].[vw_user_st_nett_report_run]
(
	RUN_DATE DATE NULL,
	REPORT_ID INT NULL,
	USER_ID NVARCHAR(MAX) NULL,
	QUERY_NAME NVARCHAR(MAX) NULL,
	RUN_TYPE NVARCHAR(MAX) NULL,
	SEND_TO_EBOSS INT NULL,
	EOD_SIM_IDS NVARCHAR(MAX) NULL,
	RUN_MONTH NVARCHAR(MAX) NULL,
	RUN_PERIOD NVARCHAR(MAX) NULL,
	SDFI_SPLIT FLOAT NULL,
	IMBALANCE_PRICE_GBP  FLOAT NULL,
	IMBALANCE_PRICE_EUR  FLOAT NULL,
	COMMODITY NVARCHAR(MAX) NULL,
	EOD_SIM_DATE NVARCHAR(MAX) NULL
)
