CREATE TABLE [endur].[vw_user_st_nett_report_deals]
(
	REPORT_ID INT NULL,
	CUSTOMER_GROUP NVARCHAR(MAX) NULL,
	COST_CENTER NVARCHAR(MAX) NULL,
	DEAL_TRACKING_NUM INT NULL,
	TRAN_NUM INT NULL,
	BUY_SELL NVARCHAR(MAX) NULL,
	CURRENCY NVARCHAR(MAX) NULL,
	DEL_MONTH NVARCHAR(MAX) NULL,
	QUANTITY FLOAT NULL,
	QUANTITY_UNIT  NVARCHAR(MAX) NULL,
	VALUE FLOAT NULL,
	DEAL_LEG INT NULL
)
