CREATE TABLE [endur].[vw_vw_portfolio_info]
(
	PFOLIO_ID INT NULL,
	PFOLIO_NAME NVARCHAR(MAX) NULL,
	PFOLIO_LONG_NAME NVARCHAR(MAX) NULL,
	PFOLIO_INFO_TYPE_NAME NVARCHAR(MAX) NULL,
	PFOLIO_INFO_VALUE NVARCHAR(MAX) NULL
)
